### ISSUE TITLE
회원가입 api 호출

### ISSUE THREAD

**Issue by Profitah** [SKHU-Capstone-Design/Frontend#20]
## :bulb: 작업 내용
서버친구가 만든  로그인 api를 비동기적으로 호출할 것이다.

## :white_check_mark: 상세 내용
- [x] 회원가입 api 호출

**Comment by Lee-gi-yeun** [comment]
로그인 한 후 나오는 모든 기능들은 토큰값을 넘겨 주셔야 해요

**Comment by Profitah** [comment]
> 로그인 한 후 나오는 모든 기능들은 토큰값을 넘겨 주셔야 해요

넵 모든 페이지에 토큰이 필요한거군요!  유의하겠습니다! ! 토큰을 처음 다뤄봐서 많이 어려워 하던 중이였는데  알려주셔서 감사합니다...!

**Comment by Profitah** [comment]
@Lee-gi-yeun  
존경하는 선배님 정말 너무 죄송한데 제가 api 호출에 어려움을 많이 겪고 있어서 호출작업 전체가  생각보다 좀 더 늦어질 것 같습니다.

가끔 만나는 서버 개발자 친구한테 살짝씩 궁금한걸 물어봤었는데 좀더 적극적으로  그 친구를  귀찮게 하거나 다른 친구들에게도 더 적극적으로 이것저것 물어보면서 보다 빠른 해결을 위해 노력하겠습니다. 

늘 선배님을 뵐 면목이 없습니다..  

제출과제가  한번 더 나오기 전까지는  꼭  api호출에 성공해보겠습니다...

**Comment by Profitah** [comment]
존경하는 선배님!  
선배님께서 카톡으로 조언해주신대로 변수설정을 했더니,  드디어 애플리케이션 JMX 서비스 URL 검색 실패 문제를 해결하고 서버실행에 성공한 것 같습니다..! 정말 감사합니다!!

<img width="376" alt="스크린샷 2024-04-22 오후 7 23 09" src="https://github.com/SKHU-Capstone-Design/Frontend/assets/101340482/a94718e7-4ef4-449b-86cf-fb9abbd02ccc">

<img width="277" alt="스크린샷 2024-04-22 오후 7 23 39"
<img width="1376" alt="스크린샷 2024-04-22 오후 7 08 41" src="https://github.com/SKHU-Capstone-Design/Frontend/assets/101340482/11392853-32b4-4f89-94b0-a457a56ca744">

 src="https://github.com/SKHU-Capstone-Design/Frontend/assets/101340482/9bf3a523-b1b0-4695-b149-55f0b53d2d7f">

**Comment by Profitah** [comment]
https://github.com/SKHU-Capstone-Design/Frontend/assets/101340482/6d10afae-89e5-440c-80b3-0ae939c5767f
